<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ToursSeeder extends Seeder
{
    public function run(): void
    {
        // Merr ID e kategorive sipas slug
        $adventureId = DB::table('categories')->where('slug', 'adventure-tours')->first()->id;
        $culturalId = DB::table('categories')->where('slug', 'cultural-tours')->first()->id;
        $beachId    = DB::table('categories')->where('slug', 'beach-getaways')->first()->id;
        $luxuryId   = DB::table('categories')->where('slug', 'luxury-escapes')->first()->id;
        $familyId   = DB::table('categories')->where('slug', 'family-vacations')->first()->id;

        DB::table('tours')->truncate();

        DB::table('tours')->insert([

            // ================= Adventure Tours =================
            [
                'category_id' => $adventureId,
                'title' => 'Swiss Alps Glacier Hike & Cable Car',
                'country' => 'switzerland',
                'location' => 'Swiss Alps',
                'days' => '7 days',
                'group' => '4–8',
                'rating' => 4.9,
                'price' => 2890,
                'image' => 'https://karlobag.eu/images/upload/750px-qz7ta.jpg',
                'desc' => 'Hike across the glacier with breathtaking views from the cable car.',
            ],
            [
                'category_id' => $adventureId,
                'title' => 'Rugova Canyon Hike',
                'country' => 'kosovo',
                'location' => 'Bjeshkët e Nemuna',
                'days' => '3 days',
                'group' => '6–12',
                'rating' => 4.7,
                'price' => 980,
                'image' => 'https://www.abenteueralbanien.de/wp-content/uploads/2023/10/Peja-Wander-Tour-Via-Ferrata-Rugova-Canyon-1-5-1024x768.jpg',
                'desc' => 'Scenic hiking through the Rugova Canyon with Via Ferrata segments.',
            ],
            [
                'category_id' => $adventureId,
                'title' => 'Snake River Whitewater Rafting',
                'country' => 'usa',
                'location' => 'Jackson Hole, Wyoming',
                'days' => '5 days',
                'group' => '4–10',
                'rating' => 4.8,
                'price' => 1990,
                'image' => 'https://img2.10bestmedia.com/Images/Photos/422408/Dave-Hansen-Whitewater-and-Scenic-River-Trips_54_990x660.jpg?auto=webp&width=3840&quality=75',
                'desc' => 'Rafting on the Snake River rapids, suitable for beginners as well.',
            ],
            [
                'category_id' => $adventureId,
                'title' => 'Dolomites Scenic Cycling',
                'country' => 'italy',
                'location' => 'Dolomites',
                'days' => '4 days',
                'group' => '2–8',
                'rating' => 4.8,
                'price' => 1690,
                'image' => 'https://www.backroads.com/sites/default/files/styles/itinerary_533/public/2023/BSII_AOP_ST_22_094_VAR_0.jpg.webp?itok=-l1_SSZu',
                'desc' => 'Cycling through alpine roads, picturesque villages, and gourmet stops.',
            ],
            [
                'category_id' => $adventureId,
                'title' => 'Shiraito Falls & Fuji Foothills Trek',
                'country' => 'japan',
                'location' => 'Honshu',
                'days' => '2 days',
                'group' => '4–12',
                'rating' => 4.9,
                'price' => 1250,
                'image' => 'https://cdn.outsideonline.com/wp-content/uploads/2023/11/Japan_JNTO_h.jpg',
                'desc' => 'Forest trails around the Shiraito waterfalls at the foothills of Mount Fuji.',
            ],
            [
                'category_id' => $adventureId,
                'title' => 'Santorini ATV Coast Ride',
                'country' => 'greece',
                'location' => 'Santorini',
                'days' => '3 days',
                'group' => '2–6',
                'rating' => 4.8,
                'price' => 1190,
                'image' => 'https://focusgreece.com/wp-content/uploads/2018/09/Greece-ATV.jpeg',
                'desc' => 'ATV adventure along the coastline, white villages, and breathtaking views.',
            ],

            // ================= Cultural Tours =================
            [
                'category_id' => $culturalId,
                'title' => 'Prizren Old Town & Shadërvan',
                'country' => 'kosovo',
                'location' => 'Prizren',
                'days' => '2 days',
                'group' => '6–14',
                'rating' => 4.8,
                'price' => 390,
                'image' => 'https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/22/75/28.jpg',
                'desc' => 'Historic stone bridge, Ottoman-era houses, and traditional dishes in the bazaar.',
            ],
            [
                'category_id' => $culturalId,
                'title' => 'Swiss Mountain Villages & Alpine Heritage',
                'country' => 'switzerland',
                'location' => 'Zermatt & Valais',
                'days' => '7 days',
                'group' => '4–8',
                'rating' => 4.9,
                'price' => 2890,
                'image' => 'https://media.vintrica.com/tr:f-auto/Kultur%20Schweiz.jpg',
                'desc' => 'Discover chalets, local cheese-making, folklore traditions, and panoramic trains.',
            ],
            [
                'category_id' => $culturalId,
                'title' => 'Washington, D.C. Monuments & Museums',
                'country' => 'usa',
                'location' => 'Washington, D.C.',
                'days' => '5 days',
                'group' => '4–10',
                'rating' => 4.8,
                'price' => 1990,
                'image' => 'https://cdn.tourradar.com/s3/tour/360x210/273451_661ea3c71356e.jpg',
                'desc' => 'Guided visits to Capitol, Lincoln Memorial, Smithsonian museums along National Mall.',
            ],
            [
                'category_id' => $culturalId,
                'title' => 'Rome Neighborhoods & Food Walk',
                'country' => 'italy',
                'location' => 'Rome',
                'days' => '4 days',
                'group' => '2–8',
                'rating' => 4.8,
                'price' => 1690,
                'image' => 'https://media.bookmundi.com/files/agency/trafalgar/cropped/products/8dc1bba7-e594-48c8-82f3-4b112314e362.jpg',
                'desc' => 'Wander cobblestone lanes, Baroque squares, and taste trattoria classics.',
            ],
            [
                'category_id' => $culturalId,
                'title' => 'Kyoto Temples & Higashiyama District',
                'country' => 'japan',
                'location' => 'Kyoto',
                'days' => '2 days',
                'group' => '4–12',
                'rating' => 4.9,
                'price' => 1250,
                'image' => 'https://i0.wp.com/www.touristjapan.com/wp-content/uploads/2023/10/Kiyomizu-dera-temple-in-autumn-on-sunset-sky-at-Kyoto-Japan-1.jpg',
                'desc' => 'Explore Kiyomizu-dera, wooden streets of Higashiyama, tea ceremony, gardens.',
            ],
            [
                'category_id' => $culturalId,
                'title' => 'Athens Acropolis & Plaka Stroll',
                'country' => 'greece',
                'location' => 'Athens',
                'days' => '3 days',
                'group' => '2–6',
                'rating' => 4.8,
                'price' => 1190,
                'image' => 'https://theodorevoyages.fr/en/wp-content/uploads/sites/3/2020/09/009-1.jpg',
                'desc' => 'Discover the Parthenon, Acropolis Museum, and stroll Plaka at sunset.',
            ],

            // ================= Beach Getaways =================
            [
                'category_id' => $beachId,
                'title' => 'Kosovo Alpine Lakes – Rugova & Sharr',
                'country' => 'kosovo',
                'location' => 'Rugova / Sharr',
                'days' => '2 days',
                'group' => '6–14',
                'rating' => 4.8,
                'price' => 390,
                'image' => 'https://toplist.info/images/800px/best-lakes-to-visit-in-kosovo-916979.jpg',
                'desc' => 'Emerald mountain lakes, swim, hike, and picnic with alpine views.',
            ],
            [
                'category_id' => $beachId,
                'title' => 'Lake Brienz & Iseltwald – Swiss Escape',
                'country' => 'switzerland',
                'location' => 'Bernese Oberland',
                'days' => '7 days',
                'group' => '4–8',
                'rating' => 4.9,
                'price' => 2890,
                'image' => 'https://static.wixstatic.com/media/f35571_b917b1505c5849ed9621d865a8f5ae50~mv2.webp',
                'desc' => 'Bright-blue water, flower promenades, and storybook villages.',
            ],
            [
                'category_id' => $beachId,
                'title' => 'Hanauma Bay Snorkel Escape',
                'country' => 'usa',
                'location' => 'Oahu, Hawaii',
                'days' => '5 days',
                'group' => '4–10',
                'rating' => 4.8,
                'price' => 1990,
                'image' => 'https://cdn.enjoytravel.com/img/Big7Enjoy/us/travel-news/places-to-visit/the-50-best-beaches-in-america/the-50-best-beaches-in-america-hero_medium_768.webp',
                'desc' => 'Snorkel coral bay with glass-clear water and golden sand.',
            ],
            [
                'category_id' => $beachId,
                'title' => 'Tropea & Calabria Coast',
                'country' => 'italy',
                'location' => 'Calabria',
                'days' => '4 days',
                'group' => '2–8',
                'rating' => 4.8,
                'price' => 1690,
                'image' => 'https://www.citalia.com/-/media/Bynder/Citalia-destinations/Italy/Coast/Calabria/Destination/Calabria-2021-Coast-001-050961-Hybris.jpg',
                'desc' => 'Clifftop towns, Caribbean-blue coves, beach time, and sunsets.',
            ],
            [
                'category_id' => $beachId,
                'title' => 'Okinawa Beaches & Coral Lagoons',
                'country' => 'japan',
                'location' => 'Okinawa',
                'days' => '2 days',
                'group' => '4–12',
                'rating' => 4.9,
                'price' => 1250,
                'image' => 'https://www.planetware.com/wpimages/2020/06/japan-best-beaches-okinawa-beaches.jpg',
                'desc' => 'Tropical sands, snorkeling, island vibes, vibrant reefs.',
            ],
            [
                'category_id' => $beachId,
                'title' => 'Paleokastritsa Coves by Boat',
                'country' => 'greece',
                'location' => 'Corfu',
                'days' => '3 days',
                'group' => '2–6',
                'rating' => 4.8,
                'price' => 1190,
                'image' => 'https://www.solmarvillas.com/sites/default/files/inline-images/best-beaches-in-greece-paleokastritsa_0.jpg',
                'desc' => 'Hop between hidden caves and turquoise coves by boat.',
            ],

            // ================= Luxury Escapes =================
            [
                'category_id' => $luxuryId,
                'title' => 'Rugova & Sharr Mountain Spa Retreat',
                'country' => 'kosovo',
                'location' => 'Rugova / Sharr',
                'days' => '2 days',
                'group' => '6–14',
                'rating' => 4.8,
                'price' => 390,
                'image' => 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/546388031.jpg?k=291942c447de80b9f76d3480fc141f18c763aacb90420286a4d2b8bf6097284e&o=&hp=1',
                'desc' => 'Five-star alpine lodge with indoor pool and spa zones.',
            ],
            [
                'category_id' => $luxuryId,
                'title' => 'Chalet Zermatt Peak',
                'country' => 'switzerland',
                'location' => 'Les Orres, Hautes-Alpes',
                'days' => '7 days',
                'group' => '4–8',
                'rating' => 4.9,
                'price' => 2890,
                'image' => 'https://www.myboutiquehotel.com/photos/111849/alpin-cocoon-les-orres-102-29036-600x350.jpg',
                'desc' => 'Geodesic dome suite, snow forests, and gourmet breakfasts.',
            ],
            [
                'category_id' => $luxuryId,
                'title' => 'Luxury Mountain Lodge & Heated Pool',
                'country' => 'usa',
                'location' => 'Mountain West',
                'days' => '5 days',
                'group' => '4–10',
                'rating' => 4.8,
                'price' => 1990,
                'image' => 'https://images.luxuryescapes.com/fl_progressive,q_auto:best,dpr_2.0/9rpswkju93b6i1s4ammq',
                'desc' => 'Stone lodge, heated pool, firepits, full-service spa.',
            ],
            [
                'category_id' => $luxuryId,
                'title' => 'Lake Como Luxury Retreat – Tremezzo',
                'country' => 'italy',
                'location' => 'Lake Como',
                'days' => '4 days',
                'group' => '2–8',
                'rating' => 4.8,
                'price' => 1690,
                'image' => 'https://www.careofcarl.fr/dokument/bibliotek/Image/CARL_Magazine/Livsstil/2022/20220426-Femklassiska/tremezzo.jpg',
                'desc' => 'Belle Époque hotel, floating pool, gardens, private boat.',
            ],
            [
                'category_id' => $luxuryId,
                'title' => 'Hakone Private Onsen Villa',
                'country' => 'japan',
                'location' => 'Hakone',
                'days' => '2 days',
                'group' => '4–12',
                'rating' => 4.9,
                'price' => 1250,
                'image' => 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/416306907.jpg?k=0c6aad73639975fe44415fd95a33a97c8e1d8411f375be518622fa78ead829f9&o=&hp=1',
                'desc' => 'Ryokan-style suite, hot-spring bath, tatami lounge.',
            ],
            [
                'category_id' => $luxuryId,
                'title' => 'Santorini Cliffside Villa, Caldera View',
                'country' => 'greece',
                'location' => 'Oia, Santorini',
                'days' => '3 days',
                'group' => '2–6',
                'rating' => 4.8,
                'price' => 1190,
                'image' => 'https://q-xx.bstatic.com/xdata/images/hotel/max500/367190993.jpg?k=509d05a67e753dc4599d7b30e939ac40813bc2c4ada57b6909bc763f12fc4c06&o=',
                'desc' => 'Suite with terrace pool, sunset cocktails, private cruise.',
            ],

            // ================= Family Vacations =================
            [
                'category_id' => $familyId,
                'title' => 'Brezovica Family Ski Break',
                'country' => 'kosovo',
                'location' => 'Brezovica, Sharr',
                'days' => '2 days',
                'group' => '6–14',
                'rating' => 4.8,
                'price' => 390,
                'image' => 'https://gdb.rferl.org/01000000-0a00-0242-c09b-08dc1e56251b_w1071_r1_s_d3.jpg',
                'desc' => 'Family-friendly skiing at Brezovica with sledding spots.',
            ],
            [
                'category_id' => $familyId,
                'title' => 'Oeschinensee Family Day — Boats & Trails',
                'country' => 'switzerland',
                'location' => 'Bernese Oberland',
                'days' => '7 days',
                'group' => '4–8',
                'rating' => 4.9,
                'price' => 2890,
                'image' => 'https://www.shutterstock.com/image-photo/happy-family-travaling-switzerland-oeschinensee-600w-2183520129.jpg',
                'desc' => 'Pedal boats, stroller paths, and picnic spots with views.',
            ],
            [
                'category_id' => $familyId,
                'title' => 'Florida Theme Parks Family Escape',
                'country' => 'usa',
                'location' => 'Orlando, Florida',
                'days' => '5 days',
                'group' => '4–10',
                'rating' => 4.8,
                'price' => 1990,
                'image' => 'https://travelarii.com/blog/wp-content/uploads/2024/08/These-Florida-Family-Vacation-Spots-That-Will-Hit-the-Nail-on-the-Head-%E2%80%93-Guaranteed.jpg',
                'desc' => 'World-class parks, rides, character meet-and-greets, pool downtime.',
            ],
            [
                'category_id' => $familyId,
                'title' => 'Tropea & Calabria Coast — Family Beach Days',
                'country' => 'italy',
                'location' => 'Calabria',
                'days' => '4 days',
                'group' => '2–8',
                'rating' => 4.8,
                'price' => 1690,
                'image' => 'https://media.bookmundi.com/aggregate-hero-images/italy/family-tour-packages/cropped.jpg',
                'desc' => 'Shallow coves, gelato strolls, golden-hour photos.',
            ],
            [
                'category_id' => $familyId,
                'title' => 'Nara Deer Park & Kyoto Family Strolls',
                'country' => 'japan',
                'location' => 'Nara & Kyoto',
                'days' => '2 days',
                'group' => '4–12',
                'rating' => 4.9,
                'price' => 1250,
                'image' => 'https://cdn.tourradar.com/s3/tour/750x400/204231_654c80233569b.jpg',
                'desc' => 'Feed deer in Nara, wander temple gardens and quiet lanes.',
            ],
            [
                'category_id' => $familyId,
                'title' => 'Corfu Family Beach Day — Paleokastritsa',
                'country' => 'greece',
                'location' => 'Corfu',
                'days' => '3 days',
                'group' => '2–6',
                'rating' => 4.8,
                'price' => 1190,
                'image' => 'https://veronicahanson.com/wp-content/uploads/2023/11/3-Best-Kept-Secret-Family-Vacation-Spots.jpg',
                'desc' => 'Play in gentle surf, boat ride to coves, family-friendly beach clubs.',
            ],
        ]);
    }
}
