<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TourDetail;
use Illuminate\Support\Facades\DB;

class TourDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tour_details')->truncate();
        $tours = [
            // ===== Adventure ========================================
            [
                'id' => 1,
                'category_slug' => "adventure",
                'destination' => "Switzerland",
                'hero_title' => "Swiss Alps Glacier Hike & Cable Car",
                'hero_image' => "https://matterhornalpinecrossing.com/ZBAG/04_matterhorn-alpine-crossing/03-keyvisuals/1788/image-thumb__1788__content-hero-small/ZBAG%20MAC%20Tag%20der%20offenen%20Bahn-36.jpg",
                'price' => 2890,
                'days' => "7 days",
                'rating' => 4.9,
                'overview' => "Experience the beauty of the Swiss Alps with the Glacier Hike & Cable Car. Enjoy a scenic ride offering breathtaking views of snow-covered peaks, then explore the glacier on foot with a guided hike. This unique adventure combines stunning landscapes, fresh mountain air, and unforgettable moments in one of Switzerland’s most iconic destinations",
                'highlights' => ["Guided Glacier Hike", "Cable Car Ride", "Local Swiss Cuisine", "Small Group Experience"],
                'gallery' => [
                    "https://media.tacdn.com/media/attractions-splice-spp-674x446/12/78/7d/c1.jpg",
                    "https://media.jungfrau.ch/image/upload/ar_16:9,c_crop,fl_lossy,q_auto/c_scale,w_964/v1606297087/fileadmin/Landingpages/Eiger-Express-Grindelwald-Eigernordwand-Weitansicht-Winter.jpg",
                    "https://matterhornalpinecrossing.com/ZBAG/04_matterhorn-alpine-crossing/03-keyvisuals/1788/image-thumb__1788__content-hero-small/ZBAG%20MAC%20Tag%20der%20offenen%20Bahn-36.jpg",
                ],
                'location' => [
                    'description' => "This tour takes place in the heart of the Swiss Alps, near the Jungfrau region.",
                    'nearestCity' => "Interlaken",
                    'groupSize' => "4 - 8 People",
                    'bestSeason' => "May – September",
                    'mapSrc' => "https://www.google.com/maps?q=Interlaken%20Switzerland&output=embed",
                ],
            ],
            [
                'id' => 2,
                'category_slug' => "adventure",
                'destination' => "Kosovo",
                'hero_title' => "Rugova Canyon Adventure",
                'hero_image' => "https://pejatourism.org/wp-content/uploads/2023/08/DB-Informatori2021-31-scaled.jpg",
                'price' => 800,
                'days' => "7 days",
                'rating' => 4.7,
                'overview' => "Rugova Valley, located in western Kosovo near the city of Peja, is one of the country’s most stunning natural attractions. Known for its dramatic mountains, deep gorges, waterfalls, and alpine meadows, Rugova is a paradise for hiking, climbing, and outdoor adventures. Visitors can enjoy breathtaking views, traditional villages, and a peaceful atmosphere that makes it a perfect escape into nature.",
                'highlights' => ["Hiking Trails", "Waterfalls & Caves", "Alpine Meadows", "Traditional Villages"],
                'gallery' => [
                    "https://pbs.twimg.com/media/CkLOOmkWUAENPkJ.jpg:large",
                    "https://pejatourism.org/wp-content/uploads/2023/08/IMG_20191020_140534-scaled.jpg",
                    "https://tourismforfuture.com/wp-content/uploads/2023/09/gryka.jpg",
                ],
                'location' => [
                    'description' => "Located in Rugova, near Peja. Dramatic canyons and alpine terrain.",
                    'nearestCity' => "Peja",
                    'groupSize' => "6 - 12 People",
                    'bestSeason' => "April – October",
                    'mapSrc' => "https://www.google.com/maps?q=Rugova%20Canyon&output=embed",
                ],
            ],
            [
                'id' => 3,
                'category_slug' => "adventure",
                'destination' => "USA",
                'hero_title' => "Snake River Whitewater Rafting",
                'hero_image' => "https://media.oars.com/wp-content/uploads/2024/08/19173738/MAS7-1536x1024.jpg",
                'price' => 2350,
                'days' => "6 days",
                'rating' => 4.7,
                'overview' => "Experience the thrill of whitewater rafting on the Snake River in the heart of the American West. Navigate powerful rapids, enjoy stunning canyon views, and feel the adrenaline as you conquer the river’s twists and turns. This adventure is perfect for thrill-seekers and nature lovers looking for an unforgettable outdoor experience.",
                'highlights' => ["Thrilling Rapids", "Scenic Canyons & Wildlife", "Guided Adventure Tours"],
                'gallery' => [
                    "https://www.responsiblevacation.com/imagesClient/S_272350.jpg",
                    "https://media.oars.com/wp-content/uploads/2024/08/19174744/MAS-MFS7-1536x1024.jpg",
                    "https://www.americanwhitewater.org//image/images/big/888736",
                ],
                'location' => [
                    'description' => "Snake River, near Jackson Hole, Wyoming, USA",
                    'nearestCity' => "Jackson",
                    'groupSize' => "4 - 12 People",
                    'bestSeason' => "March – May / Sep – Nov",
                    'mapSrc' => "https://www.google.com/maps?q=Snake+River,+Wyoming,+USA&output=embed",
                ],
            ],
            [
                'id' => 4,
                'category_slug' => "adventure",
                'destination' => "Italy",
                'hero_title' => "Dolomites Scenic Cycling",
                'hero_image' => "https://www.wildkogel-arena.at/site/assets/files/2560/mountainbiken-sonnenaufgang.1920x0-sp.jpg",
                'price' => 1890,
                'days' => "8 days",
                'rating' => 4.8,
                'overview' => "Explore the breathtaking Dolomites by bike on a scenic cycling adventure through towering peaks, winding mountain roads, and picturesque alpine villages. This experience combines stunning landscapes, fresh mountain air, and a chance to immerse yourself in Italy’s natural beauty, perfect for cycling enthusiasts and nature lovers alike.",
                'highlights' => ["Scenic Mountain Routes", "Alpine Villages & Culture", "Breathtaking Panoramic Views"],
                'gallery' => [
                    "https://cdn.world-discovery.com/24919/dolomites-ebiketour-scaled-7.webp",
                    "https://media.istockphoto.com/id/1329482439/photo/senior-woman-on-electric-mountain-bike-below-sassolungo-summit-dolomites-italy.jpg?s=612x612&w=0&k=20&c=vYo27ZQy4MYcW0fRU16F62iGK09EruTN61Ijjpz07JE=",
                    "https://d2exd72xrrp1s7.cloudfront.net/www/collection/745/1FP5Q6?width=&height=&crop=&q=40",
                ],
                'location' => [
                    'description' => "Dolomites, Northern Italy",
                    'nearestCity' => "Cortina d'Ampezzo",
                    'groupSize' => "4 - 12 People",
                    'bestSeason' => "May – September",
                    'mapSrc' => "https://www.google.com/maps?q=Cortina+d'Ampezzo,+Italy&output=embed",
                ],
            ],
            [
                'id' => 5,
                'category_slug' => "adventure",
                'destination' => "Japan",
                'hero_title' => "Shiraito Falls & Fuji Foothills Trek",
                'hero_image' => "https://static.gltjp.com/glt/data/directory/12000/11593/20210621_041217_9c3a793b_w1920.webp",
                'price' => 1950,
                'days' => "4 days",
                'rating' => 4.9,
                'overview' => "Discover the serene beauty of Shiraito Falls and the surrounding Fuji foothills on this scenic trek in Japan. Walk through lush forests, admire cascading waterfalls, and enjoy breathtaking views of Mount Fuji. This adventure is perfect for nature lovers and hikers seeking a peaceful yet inspiring outdoor experience.",
                'highlights' => ["Shiraito Waterfalls", "Scenic Forest Trails", "Mount Fuji Views", "Peaceful Nature Experience"],
                'gallery' => [
                    "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/36/e6/8c/photo-shot-while-going.jpg?w=900&h=500&s=1",
                    "https://mediaim.expedia.com/destination/1/1178e51cd4f908b9451f2f1102bc9b64.jpg",
                    "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/47/2c/ed/caption.jpg?w=800&h=800&s=1",
                ],
                'location' => [
                    'description' => "Routes via Yoshida Trail with nearby onsen towns for recovery.",
                    'nearestCity' => "Fujiyoshida",
                    'groupSize' => "4 - 10 People",
                    'bestSeason' => "July – September",
                    'mapSrc' => "https://www.google.com/maps?q=Mount%20Fuji&output=embed",
                ],
            ],
            [
                'id' => 6,
                'category_slug' => "adventure",
                'destination' => "Greece",
                'hero_title' => "Santorini ATV Coastal Ride",
                'hero_image' => "https://www.pausethemoment.com/wp-content/uploads/2015/09/P1480354.jpg",
                'price' => 1190,
                'days' => "5 days",
                'rating' => 4.8,
                'overview' => "Explore the stunning coastline of Santorini on an exciting ATV adventure. Ride through scenic cliffs, volcanic landscapes, and charming villages while enjoying panoramic views of the Aegean Sea. This tour is perfect for thrill-seekers and those looking to discover the island in a fun and unique way.",
                'highlights' => ["ATV Adventure", "Seaside Views", "Cliffside Trails"],
                'gallery' => [
                    "https://media.tacdn.com/media/attractions-splice-spp-674x446/15/d7/db/10.jpg",
                    "https://cdn.getyourguide.com/image/format=auto,fit=crop,gravity=auto,quality=60,width=450,height=450,dpr=2/tour_img/4b23785e7bf22d81da8d6bb2bb16d51150f4b3dc4a5f23bc9d4968804891ad70.jpeg",
                    "https://www.theblondeabroad.com/wp-content/uploads/2020/08/DSCF0169-712x520.jpg",
                ],
                'location' => [
                    'description' => "Ride along scenic cliffs and coastal paths with stops in charming villages.",
                    'nearestCity' => "Fira",
                    'groupSize' => "2 - 8 People",
                    'bestSeason' => "April – October",
                    'mapSrc' => "https://www.google.com/maps?q=Santorini,+Greece&output=embed",
                ],
            ],


            // ===== Culture ============================================================
            [
                'id' => 7,
                'category_slug' => "culture",
                'destination' => "Kosovo",
                'hero_title' => "Prizren Old Town & shadërvan",
                'hero_image' => "https://portaltriptips.com.br/wp-content/uploads/2025/02/Atracoes-de-Prizren-Kosovo-Westen61.jpg",
                'price' => 390,
                'days' => "5 days",
                'rating' => 4.6,
                'overview' => "Prizren Old Town is the cultural heart of Kosovo, where Ottoman-era architecture, cobblestone streets, and lively cafés meet. At Shadërvan Square, visitors enjoy the vibrant atmosphere, traditional food, and a true blend of history and local life.",
                'highlights' => ["Historic Old Town", "Shadërvan Square", "Prizren Fortress Views", "Cultural Vibe"],
                'gallery' => [
                    "https://mediaim.expedia.com/localexpert/988946/f914545c-30fd-4820-9d66-a87454ccf832.jpg",
                    "https://wander-lush.org/wp-content/uploads/2021/09/Emily-Lush-Prizren-Kosovo-river-bridge-hero.jpg",
                    "https://wander-lush.org/wp-content/uploads/2019/05/Emily-Lush-Prizren-2.jpg",
                ],
                'location' => [
                    'description' => "Explore Prizren’s historic center, Ottoman bridges, and vibrant Shadërvan Square.",
                    'nearestCity' => "Prizren",
                    'groupSize' => "2 - 12 People",
                    'bestSeason' => "April – October",
                    'mapSrc' => "https://www.google.com/maps?q=Prizren%20Shadervan&output=embed",
                ],
            ],
            [
                'id' => 8,
                'category_slug' => "culture",
                'destination' => "Switzerland",
                'hero_title' => "Swiss Mountain Villages & Alpine Heritage",
                'hero_image' => "https://images.news18.com/ibnlive/uploads/2024/09/switzerland-2024-09-3d8eb0ddcdbb9ed59db31e15b54a4ea3-16x9.jpg",
                'price' => 2890,
                'days' => "3 days",
                'rating' => 4.7,
                'overview' => "Step into the heart of Swiss culture by exploring picturesque mountain villages nestled among the Alps. From wooden chalets adorned with flowers to cobblestone streets and historic churches, these villages reflect centuries of alpine heritage. Visitors can experience traditional Swiss life, taste local cuisine, and enjoy breathtaking views of snow-capped peaks, making it a perfect blend of culture, history, and natural beauty.",
                'highlights' => ["Alpine Villages", "Traditional Swiss Culture", "Scenic Mountain Views", "Local Cuisine"],
                'gallery' => [
                    "https://i.ytimg.com/vi/AERHuUExvcw/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCAgalAgxHxPMN498oEKmXO9FCF3g",
                    "https://i0.wp.com/blog.lowcostvibes.com/wp-content/uploads/2023/03/Explore-beautiful-Swiss-Alps-and-top-tourist-destinations-in-Switzerland.png?fit=1200%2C680&ssl=1",
                    "https://d3m7xw68ay40x8.cloudfront.net/assets/2024/06/TRIPS-Train-Travel-Swiss-Alps-2.jpg",
                ],
                'location' => [
                    'description' => "Explore charming Swiss villages, traditional chalets, and alpine landscapes.",
                    'nearestCity' => "Interlaken",
                    'groupSize' => "2 - 12 People",
                    'bestSeason' => "June – September",
                    'mapSrc' => "https://www.google.com/maps?q=Swiss%20Alps&output=embed",
                ],
            ],
            [
                'id' => 9,
                'category_slug' => "culture",
                'destination' => "USA",
                'hero_title' => "Washington, D.C. Monuments & Museums",
                'hero_image' => "https://www.visittheusa.com/sites/default/files/styles/hero_l/public/images/hero_media_image/2016-10/National%20Mall.jpg?itok=jK3fmbqW",
                'price' => 1990,
                'days' => "4 days",
                'rating' => 4.8,
                'overview' => "Discover the rich history and vibrant culture of the U.S. capital on this comprehensive tour of Washington, D.C. Explore iconic national monuments, including the Lincoln Memorial and Washington Monument, stroll through world-class Smithsonian museums, and visit historic landmarks like Capitol Hill and the White House. Along the way, learn about the stories behind these sites, experience the city’s architectural beauty, and immerse yourself in the traditions and heritage that define the heart of the nation.",
                'highlights' => ["National Monuments", "Smithsonian Museums", "Historic Landmarks", "Cultural Experience"],
                'gallery' => [
                    "https://i.guim.co.uk/img/media/708d7f692718744b503d045f5eb6a37747a84456/0_201_4096_2459/master/4096.jpg?width=465&dpr=1&s=none&crop=none",
                    "https://www.trawell.in/blog/wp-content/uploads/2022/08/National_Museum_of_American_History_Main.jpg",
                    "https://www.capitalregionusa.org/sites/default/files/styles/content_slideshow_image/public/legacy_images/HP_Jefferson%20Memorial.jpg?itok=-41ggrPA",
                ],
                'location' => [
                    'description' => "Visit the key monuments, memorials, and museums in the heart of Washington, D.C.",
                    'nearestCity' => "Washington, D.C.",
                    'groupSize' => "2 - 15 People",
                    'bestSeason' => "March – October",
                    'mapSrc' => "https://www.google.com/maps?q=Washington%20DC&output=embed",
                ],
            ],
            [
                'id' => 10,
                'category_slug' => "culture",
                'destination' => "Italy",
                'hero_title' => "Rome Neighborhoods & Food Walk",
                'hero_image' => "https://theabroadguide.com/wp-content/uploads/2025/02/trastevere_s_best_dining_spots.jpg",
                'price' => 1690,
                'days' => "3 days",
                'rating' => 4.8,
                'overview' => "Explore the vibrant neighborhoods of Rome while tasting authentic Italian cuisine. Wander through charming streets, discover local markets, and enjoy traditional dishes, getting a true taste of the city’s culture and flavors.",
                'highlights' => ["Local Food Tasting", "Historic Neighborhoods", "Street Markets", "Cultural Experience"],
                'gallery' => [
                    "https://www.falcortravels.com/wp-content/uploads/2018/10/food_tour_in_the_trastevere_1-1.jpg",
                    "https://media.istockphoto.com/id/1172170240/photo/restaurants-and-cafes-in-rome-italy.jpg?s=612x612&w=0&k=20&c=U-MEhYM096S8ENnuMogid4vBcB0Fc0Fp23XRvw9qMtY=",
                    "https://www.citalia.com/-/media/Bynder/Citalia-destinations/Italy/Cities/Rome/Rome-2022-Trastevere-Street-1557845780-Hybris.jpg?rev=78a87604caaa4fb596a0d304f069f9e3&hash=5124D829504CE7706779C73004D368CF&w=1920&h=940",
                ],
                'location' => [
                    'description' => "Discover Rome’s iconic neighborhoods, enjoy local food, and experience the city like a true Roman.",
                    'nearestCity' => "Rome",
                    'groupSize' => "2 - 12 People",
                    'bestSeason' => "March – October",
                    'mapSrc' => "https://www.google.com/maps?q=Rome&output=embed",
                ],
            ],
            [
                'id' => 11,
                'category_slug' => "culture",
                'destination' => "Japan",
                'hero_title' => "Kyoto Temples & Higashiyama District",
                'hero_image' => "https://d1a1ntgk1j6wes.cloudfront.net/2015/021-Yasaka-Pagoda-and-Sannen-Zaka-Street-in-the-Morning-Higashiyama-Kyoto-Japan.jpg",
                'price' => 1250,
                'days' => "8 days",
                'rating' => 4.9,
                'overview' => "Explore Kyoto’s historic temples and the picturesque streets of the Higashiyama District. Experience traditional Japanese culture, stroll through narrow alleys lined with wooden shops, and admire beautiful temples, shrines, and gardens.",
                'highlights' => ["Historic Temples", "Traditional Streets", "Cultural Experience", "Scenic Gardens"],
                'gallery' => [
                    "https://d3bbatwdaufxg9.cloudfront.net/content/5914/5811/5072/03-20140317_Gion_Hanatourou-148.jpg",
                    "https://img.freepik.com/premium-photo/sunset-ancient-pagoda-toji-temple-autumn-garden-kyoto-japan-tallest-wooden-pagoda-japan_199107-660.jpg",
                    "https://assets.hldycdn.com/articles/4eeb57_3b1226202ba6458fa9a85debf2e4faca~mv2.jpg",
                ],
                'location' => [
                    'description' => "Visit Kyoto’s Higashiyama District and explore its temples, shrines, and traditional streets.",
                    'nearestCity' => "Kyoto",
                    'groupSize' => "2 - 10 People",
                    'bestSeason' => "March – November",
                    'mapSrc' => "https://www.google.com/maps?q=Kyoto+Higashiyama&output=embed",
                ],
            ],
            [
                'id' => 12,
                'category_slug' => "culture",
                'destination' => "Greece",
                'hero_title' => "Athens Acropolis & Plaka Walk",
                'hero_image' => "https://cdn.kimkim.com/files/a/content_articles/featured_photos/ce519d441b5497e2f74c63098a3ce3fca214543f/big-f694292866e7e7c6386f8af7167c73b8.jpg",
                'price' => 1190,
                'days' => "6 days",
                'rating' => 4.9,
                'overview' => "Discover the rich history of Athens by visiting the iconic Acropolis and wandering through the charming Plaka district. Experience ancient ruins, neoclassical architecture, and vibrant streets filled with shops and local culture.",
                'highlights' => ["Acropolis Visit", "Historic Plaka District", "Ancient Ruins", "Cultural Experience"],
                'gallery' => [
                    "https://www.gpsmycity.com/img/gd/1587.jpg",
                    "https://cdn.getyourguide.com/img/tour/9cab20c9801ab116a992eacc6f0bd23f755a6e2c97da2e01efb444b498ec5a8e.jpg/155.jpg",
                    "https://st4.depositphotos.com/1077310/29348/i/450/depositphotos_293487242-stock-photo-street-view-in-the-old.jpg",
                ],
                'location' => [
                    'description' => "Explore Athens’ Acropolis and the surrounding Plaka neighborhood, experiencing history and local culture.",
                    'nearestCity' => "Athens",
                    'groupSize' => "2 - 12 People",
                    'bestSeason' => "April – October",
                    'mapSrc' => "https://www.google.com/maps?q=Athens+Acropolis&output=embed",
                ],
            ],


            // ===== Beach Getaways =======================================================
            [
                'id' => 13,
                'category_slug' => "beach",
                'destination' => "Kosovo",
                'hero_title' => "Kosovo Alpine Lakes – Rugova & Sharr",
                'hero_image' => "https://pejatourism.org/wp-content/uploads/2023/08/DB-Informatori2021-31-scaled.jpg",
                'price' => 390,
                'days' => "2 days",
                'rating' => 4.8,
                'overview' => "Although Kosovo is landlocked, the Sharr Mountains and Rugova offer stunning alpine lakes with crystal-clear waters. A hidden paradise for those seeking a peaceful getaway in nature with fresh air, hiking opportunities, and breathtaking mountain views.",
                'highlights' => ["Alpine Lakes", "Hiking Trails", "Mountain Scenery", "Peaceful Atmosphere"],
                'gallery' => [
                    "https://www.abenteueralbanien.de/wp-content/uploads/2023/10/Peja-Wander-Tour-Via-Ferrata-Rugova-Canyon-1-18-1014x1024.jpg",
                    "https://pbs.twimg.com/media/CkLOOmkWUAENPkJ.jpg:large",
                    "https://www.kosovo-vacations.com/ressourcen/images/kosovos-mountains-gjeravica.jpg",
                ],
                'location' => [
                    'description' => "Explore the stunning alpine lakes of Rugova and the Sharr Mountains, surrounded by pristine nature and scenic landscapes.",
                    'nearestCity' => "Pejë",
                    'groupSize' => "2 - 10 People",
                    'bestSeason' => "June – September",
                    'mapSrc' => "https://www.google.com/maps?q=Rugova+Alpine+Lakes&output=embed",
                ],
            ],
            [
                'id' => 14,
                'category_slug' => "beach",
                'destination' => "Switzerland",
                'hero_title' => "Lake Brienz & Iseltwald – Swiss Escape",
                'hero_image' => "https://as2.ftcdn.net/jpg/05/37/19/09/1000_F_537190931_aMlbu1Q9QitqKpf7O5CpEaZLMrLyOC9J.jpg",
                'price' => 2890,
                'days' => "7 days",
                'rating' => 4.9,
                'overview' => "Enjoy a relaxing escape by the turquoise waters of Lake Brienz, surrounded by the Swiss Alps. Visit Iseltwald village, take scenic boat rides, and unwind by the peaceful alpine beaches.",
                'highlights' => ["Lake Views", "Boat Rides", "Alpine Village", "Turquoise Waters"],
                'gallery' => [
                    "https://www.berneseoberlandpass.ch/assets/Transport/BLS-Schifffahrt/2022-5-bls-schifffahrt-brienzersee-giessbach__FitWzE1MDAsMTUwMF0.png",
                    "https://pbs.twimg.com/media/FSGFjx-WQAA_XLO.jpg:large",
                    "https://images.squarespace-cdn.com/content/v1/51d9d37ee4b0a0494bc507c8/1435547927470-LEUGTMMDFWD4T1C8D18J/image-asset.jpeg",
                ],
                'location' => [
                    'description' => "Located in Bernese Oberland, near Interlaken.",
                    'nearestCity' => "Interlaken",
                    'groupSize' => "4 - 8 People",
                    'bestSeason' => "June – September",
                    'mapSrc' => "https://www.google.com/maps?q=Lake+Brienz+Switzerland&output=embed",
                ],
            ],
            [
                'id' => 15,
                'category_slug' => "beach",
                'destination' => "USA",
                'hero_title' => "Hanuma Bay Snorkel Escape",
                'hero_image' => "https://www.alamoanahotelhonolulu.com/Portals/alamoanahotelhonolulu.com/Images/HeroImages/hanauma-bay1_1920x720.jpg?ver=2018-08-23-164612-540",
                'price' => 1990,
                'days' => "5 days",
                'rating' => 4.8,
                'overview' => "Hanuma Bay in Hawaii offers one of the best snorkeling experiences in the world. Dive into crystal-clear waters, explore coral reefs, and swim with tropical fish in a natural paradise.",
                'highlights' => ["Snorkeling", "Coral Reefs", "Tropical Fish", "Crystal Waters"],
                'gallery' => [
                    "https://www.privatetourshawaii.com/uploads/2/4/1/4/24149144/large_orig.jpg",
                    "https://hawaii.com/wp-content/uploads/2025/04/Hanauma-Bay-scaled.jpg",
                    "https://loveoahu.org/wp-content/uploads/snorkeling-hanauma-bay-1.jpg",
                ],
                'location' => [
                    'description' => "Hanuma Bay, Oahu, Hawaii – protected marine life conservation area.",
                    'nearestCity' => "Honolulu",
                    'groupSize' => "4 - 10 People",
                    'bestSeason' => "All Year",
                    'mapSrc' => "https://www.google.com/maps?q=Hanuma+Bay+Hawaii&output=embed",
                ],
            ],
            [
                'id' => 16,
                'category_slug' => "beach",
                'destination' => "Italy",
                'hero_title' => "Tropea & Calabria Coast",
                'hero_image' => "https://images.winalist.com/blog/wp-content/uploads/2025/07/10122238/adobestock-515729288-1500x945.jpeg",
                'price' => 1590,
                'days' => "4 days",
                'rating' => 4.7,
                'overview' => "Discover Italy’s hidden gem – Tropea and the Calabria Coast. Famous for sandy beaches, crystal waters, and delicious Italian cuisine.",
                'highlights' => ["Beaches", "Italian Food", "Scenic Coastline"],
                'gallery' => [
                    "https://ita.travel/img/t390h260/blogimg/leto/calabria/tropea-oasi-beach.jpg",
                    "https://www.veratour.it/share/img/img.cfm?src=opentur/VERATOUR/cms/1217106/a-300.jpg&tmp=croppatutto&width=740&height=400",
                    "https://pohcdn.com/sites/default/files/styles/paragraph__live_banner__lb_image__1880bp/public/live_banner/Tropea.jpg",
                ],
                'location' => [
                    'description' => "Located in Calabria, Southern Italy.",
                    'nearestCity' => "Tropea",
                    'groupSize' => "2 - 8 People",
                    'bestSeason' => "May – September",
                    'mapSrc' => "https://www.google.com/maps?q=Tropea+Italy&output=embed",
                ],
            ],
            [
                'id' => 17,
                'category_slug' => "beach",
                'destination' => "Japan",
                'hero_title' => "Okinawa Beaches & Coral Lagoons",
                'hero_image' => "https://visitokinawajapan.com/wp-content/themes/visit-okinawa_multi-language/lang/en/assets/img/discover/116/di119_kv_kume-miyako-yaeyama-beaches.webp",
                'price' => 2100,
                'days' => "2 days",
                'rating' => 4.9,
                'overview' => "Okinawa offers tropical beaches, coral lagoons, and a unique blend of Japanese and island culture. Perfect for a relaxing yet exotic getaway.",
                'highlights' => ["Coral Lagoons", "Tropical Beaches", "Island Culture"],
                'gallery' => [
                    "https://tripates.com/media/japan-okinawa-best-beaches-sunayama-beach.jpg",
                    "https://tripates.com/media/japan-okinawa-best-beaches-mibaru-beach.jpg",
                    "https://preview.redd.it/0diyn3tgd2sz.jpg?width=1080&crop=smart&auto=webp&s=198925d445b8fbb14a6226fa6f5b0489a6248aa9",
                ],
                'location' => [
                    'description' => "Located in Okinawa Prefecture, southern Japan.",
                    'nearestCity' => "Naha",
                    'groupSize' => "4 - 12 People",
                    'bestSeason' => "April – October",
                    'mapSrc' => "https://www.google.com/maps?q=Okinawa+Japan&output=embed",
                ],
            ],
            [
                'id' => 18,
                'category_slug' => "beach",
                'destination' => "Greece",
                'hero_title' => "Navagio Beach (Shipwreck Beach), Zakynthos",
                'hero_image' => "https://www.jet2holidays.com/-/media/destinations/poi/greece/destinations%20review%20new%20pois%20greece/zth_navagio_beach_499618920_getty_rgb-136-dpi-for-web.jpg?h=500&w=1920&crop=1&hash=CB881478A13E18F313869E786684C36F",
                'price' => 1390,
                'days' => "3 days",
                'rating' => 4.8,
                'overview' => "Visit the iconic Navagio Beach, also known as Shipwreck Beach, on the island of Zakynthos. Famous for its crystal-clear turquoise waters, white sandy shores, and the dramatic shipwreck resting on the sand, this beach offers a stunning and unforgettable experience.",
                'highlights' => ["Shipwreck Sightseeing", "Crystal Clear Waters", "White Sandy Beach", "Scenic Views"],
                'gallery' => [
                    "https://static9.depositphotos.com/1611230/1117/i/950/depositphotos_11170386-stock-photo-navagio-beach-with-ship-wreck.jpg",
                    "https://market-resized.envatousercontent.com/photodune.net/EVA/TRX/df/64/f8/e9/c9/v1_E10/E108O1LG.jpg?auto=format&q=94&mark=https%3A%2F%2Fassets.market-storefront.envato-static.com%2Fwatermarks%2Fphoto-260724.png&opacity=0.2&cf_fit=contain&w=590&h=393&s=9588d7ea3f847f3193dc20649f42d9d6d8df884c1a7e3da7a337e5fa7252e07b",
                    "https://expertvagabond.com/wp-content/uploads/shipwreck-beach-navagio-guide.jpg",
                ],
                'location' => [
                    'description' => "Explore Navagio Beach, accessible by boat, and enjoy the breathtaking scenery of Zakynthos’ coastline.",
                    'nearestCity' => "Zakynthos Town",
                    'groupSize' => "2 - 10 People",
                    'bestSeason' => "May – September",
                    'mapSrc' => "https://www.google.com/maps?q=Navagio+Beach+Zakynthos&output=embed",
                ],
            ],



            // ===== ===========================Luxury Escapes ===============================
            [
                'id' => 19,
                'category_slug' => "luxury",
                'destination' => "Kosovo",
                'hero_title' => "Rugova & Sharr Mountain Spa Retreat",
                'hero_image' => "https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/578317836.jpg?k=9c818e2a60742cbcd88da675ede0131a84beb0e17f6d6ca6340d97af2b2891f3&o=",
                'price' => 390,
                'days' => "2 days",
                'rating' => 4.8,
                'overview' => "Unwind in the serene Sharr and Rugova Mountains with a luxury spa retreat. Experience cozy mountain lodges, traditional wellness treatments, and breathtaking alpine views. Perfect for couples or small groups seeking peace and indulgence.",
                'highlights' => ["Spa & Wellness", "Mountain Views", "Luxury Lodge", "Traditional Treatments"],
                'gallery' => [
                    "https://cf.bstatic.com/xdata/images/hotel/max1024x768/641064567.jpg?k=39b76cdc5438c183ce43c63946fe1bac822639b1701b742218ec3161ce6d9b22&o=&hp=1",
                    "https://q-xx.bstatic.com/xdata/images/hotel/max500/411454287.jpg?k=34aa361685f79d4c93f1a17bd08916faacd2a44fd410e9ec95a96d5fa5252786&o=",
                    "https://www.albinfo.at/wp-content/uploads/2020/10/121658067_349602419705828_1266022081998182003_n.jpg",
                ],
                'location' => [
                    'description' => "Relax and rejuvenate in the scenic Rugova Valley and Sharr Mountains, surrounded by nature with spa facilities and mountain views.",
                    'nearestCity' => "Pejë",
                    'groupSize' => "2 - 8 People",
                    'bestSeason' => "May – October",
                    'mapSrc' => "https://www.google.com/maps?q=Rugova+Sharr+Mountains&output=embed",
                ],
            ],
            [
                'id' => 20,
                'category_slug' => "luxury",
                'destination' => "Switzerland",
                'hero_title' => "Chalet Zermatt Peak",
                'hero_image' => "https://www.chaletzermattpeak.com/media/37691/chalet_zermatt_peak_12.jpg",
                'price' => 2890,
                'days' => "7 days",
                'rating' => 4.9,
                'overview' => "Experience ultimate luxury at Chalet Zermatt Peak, a stunning alpine retreat with breathtaking views of the Matterhorn. This chalet combines modern design with cozy alpine charm, offering private spa facilities, gourmet dining, and panoramic mountain vistas. Perfect for relaxation, skiing, and enjoying the serene beauty of Zermatt.",
                'highlights' => ["Panoramic Matterhorn views", "Private spa and sauna", "Luxury interiors with alpine charm"],
                'gallery' => [
                    "https://cf.bstatic.com/xdata/images/hotel/max1024x768/371282850.jpg?k=3651794e5fd65b390bd9e178223e0f44d1e62a74b2fef117aa491b4f151545c9&o=&hp=1",
                    "https://static.chaletowners.com/site/assets/files/15007/chalet-evening-lit-up-looking-towards-tasch.1600x0.jpg",
                    "https://www.chaletzermattpeak.com/media/45275/1-Lounge-at-sunset-with-matterhorn-in-roof.jpg",
                ],
                'location' => [
                    'description' => "Nestled above the car-free village of Zermatt, Chalet Zermatt Peak offers unparalleled privacy and panoramic views of the surrounding alpine landscape.",
                    'nearestCity' => "Zermatt, Switzerland",
                    'groupSize' => "10 adults + 3 children",
                    'bestSeason' => "December – April (ski season), June – September (summer activities)",
                    'mapSrc' => "https://www.google.com/maps?q=Chalet+Zermatt+Peak,+Triftweg+47,+3920+Zermatt,+Switzerland&output=embed"
                ],
            ],
            [
                'id' => 21,
                'category_slug' => "luxury",
                'destination' => "USA",
                'hero_title' => "Luxury Mountain Lodge & Heated Pool",
                'hero_image' => "https://www.oxfordski.com/media/73495/luxury-ski-chalet-kitzbuhel-chalet-tiffany-oxford-ski-pool.jpg",
                'price' => 1990,
                'days' => "5 days",
                'rating' => 4.8,
                'overview' => "A luxury mountain escape in the USA featuring heated pools, world-class dining, and cozy lodges. Perfect for relaxation with a touch of adventure.",
                'highlights' => ["Heated Pool", "Luxury Lodges", "Fine Dining"],
                'gallery' => [
                    "https://www.oxfordski.com/media/71335/106-4092_chalet-vilaiet_02-06-23_visciani-ph.jpg",
                    "https://a0.muscache.com/im/pictures/44743255-3e20-4f67-8db7-fc69c1dfd51c.jpg?im_w=720",
                    "https://cdn-v2.leotrippi.com/original_images/chalet-joux-plane-morzine-summer-exterior.jpg",
                ],
                'location' => [
                    'description' => "Mountain West luxury lodge, designed for indulgence and comfort.",
                    'nearestCity' => "Aspen",
                    'groupSize' => "4 - 10 People",
                    'bestSeason' => "All Year",
                    'mapSrc' => "https://www.google.com/maps?q=Aspen+Colorado&output=embed",
                ],
            ],
            [
                'id' => 22,
                'category_slug' => "luxury",
                'destination' => "Italy",
                'hero_title' => "Lake Como Luxury Retreat – Tremezzo",
                'hero_image' => "https://www.jacadatravel.com/_next/image/?url=https%3A%2F%2Fcdn.jacadatravel.com%2Fwp-content%2Fuploads%2F2016%2F08%2F12-Flowers-Pool-2.jpg&w=3840&q=100",
                'price' => 2890,
                'days' => "4 days",
                'rating' => 4.8,
                'overview' => "Enjoy the finest Italian luxury at Lake Como. Relax in a private villa with stunning views, infinity pools, and world-class service in Tremezzo.",
                'highlights' => ["Lake Como Views", "Private Villa", "Infinity Pool"],
                'gallery' => [
                    "https://www.venuereport.com/media/cache/resolve/venue_carousel/uploads/2017/09/Hotel+Grand+Tremezzo+Lake+Como+Italy-inside+elsewhere+3.jpeg",
                    "https://www.grandhoteltremezzo.com/media/iafitc4d/grand_hotel_tremezzo-roomssuites-ruben-0g5a8541.jpg?width=514&height=340&format=webp&v=1da342bfbd37bb0",
                    "https://cf.bstatic.com/xdata/images/hotel/max1024x768/529029190.jpg?k=acf0ee3605155f59a6b3911bd84bc90c7e77f0210e97f56caf7f429a833534e7&o=&hp=1",
                ],
                'location' => [
                    'description' => "Luxury retreat in Tremezzo, Lake Como.",
                    'nearestCity' => "Como",
                    'groupSize' => "2 - 8 People",
                    'bestSeason' => "April – October",
                    'mapSrc' => "https://www.google.com/maps?q=Lake+Como+Italy&output=embed",
                ],
            ],
            [
                'id' => 23,
                'category_slug' => "luxury",
                'destination' => "Japan",
                'hero_title' => "Hakone Private Onsen Villa",
                'hero_image' => "https://www.hakone-retreat.com/wordpress/wp-content/uploads/2024/08/%E9%9C%B2%E5%A4%A9%E9%A2%A8%E5%91%82_%E7%94%B7%E6%B9%AF-scaled.jpg",
                'price' => 2100,
                'days' => "2 days",
                'rating' => 4.9,
                'overview' => "Relax in a private onsen villa in Hakone. Enjoy traditional Japanese hospitality, luxury interiors, and natural hot spring baths.",
                'highlights' => ["Private Onsen", "Japanese Hospitality", "Luxury Interiors"],
                'gallery' => [
                    "https://www.thehotelguru.com/_images/53/54/5354d1ccfe34f043d4dfe15283082441/600x422.jpg",
                    "https://www.thehotelguru.com/_images/32/bc/32bccee09bb54d6ee2338f3b1759e901/s880x600.jpg",
                    "https://static.wixstatic.com/media/ceb5cd_06a4d535529c43508767859ef7221ea5~mv2.jpg/v1/fill/w_980,h_551,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/ceb5cd_06a4d535529c43508767859ef7221ea5~mv2.jpg",
                ],
                'location' => [
                    'description' => "Hakone luxury villas with private hot springs.",
                    'nearestCity' => "Hakone",
                    'groupSize' => "4 - 12 People",
                    'bestSeason' => "All Year",
                    'mapSrc' => "https://www.google.com/maps?q=Hakone+Japan&output=embed",
                ],
            ],
            [
                'id' => 24,
                'category_slug' => "luxury",
                'destination' => "Greece",
                'hero_title' => "Santorini Cliffside Villa, Caldera View",
                'hero_image' => "https://love-our-travels.com/wp-content/uploads/2020/09/g1.jpg",
                'price' => 2390,
                'days' => "3 days",
                'rating' => 4.9,
                'overview' => "Enjoy the ultimate escape in a cliffside villa with sweeping views of the Santorini caldera. Wake up to dramatic sunrises, unwind on private terraces overlooking the Aegean Sea, and experience the romance and luxury of this volcanic island. Perfect for couples or small groups seeking privacy, refined amenities, and unforgettable views in one of the world’s most iconic locations.",
                'highlights' => ["Cliffside Villa", "Infinity Pool", "Caldera Sunset Views"],
                'gallery' => [
                    "https://www.santorinivillas.co.uk/wp-content/uploads/2021/02/jacuzzi-athiri-cave-villa-oia.jpg",
                    "https://www.santorinivillas.co.uk/wp-content/uploads/2021/02/mezzo-villa-oia-views.jpg",
                    "https://i0.wp.com/theluxurytravelexpert.com/wp-content/uploads/2018/08/KATIKIES.jpg?ssl=1",
                ],
                'location' => [
                    'description' => "Luxury cliffside villas in Oia, Santorini.",
                    'nearestCity' => "Oia",
                    'groupSize' => "2 - 6 People",
                    'bestSeason' => "May – October",
                    'mapSrc' => "https://www.google.com/maps?q=Oia+Santorini&output=embed",
                ],
            ],

            // ===== Family Vacations =======================================================
            [
                'id' => 25,
                'category_slug' => "family",
                'destination' => "Kosovo",
                'hero_title' => "Brezovica Family Ski Break",
                'hero_image' => "https://blog-cdn.checkyeti.com/wp-content/uploads/2019/11/Kitzbu%CC%88hel.jpg",
                'price' => 390,
                'days' => "2 days",
                'rating' => 4.8,
                'overview' => "Spend quality time with your family in Brezovica, Kosovo’s most popular ski resort. Perfect for beginners and families, with gentle ski slopes, cozy lodges, and beautiful snowy views.",
                'highlights' => ["Family Skiing", "Cozy Lodges", "Winter Fun for Kids"],
                'gallery' => [
                    "https://www.powderhounds.com/site/DefaultSite/filesystem/images/Europe/Kosovo/Brezovica/overview/11.JPG",
                    "https://www.powderhounds.com/site/DefaultSite/filesystem/images/Europe/Kosovo/Brezovica/overview/06.jpg",
                    "https://www.skiworld.co.uk/images/uploads/photos/large/valloire_-_lifts_15831.jpg",
                ],
                'location' => [
                    'description' => "Located in Sharr Mountains, southern Kosovo.",
                    'nearestCity' => "Ferizaj / Prizren",
                    'groupSize' => "6 - 14 People",
                    'bestSeason' => "December – March",
                    'mapSrc' => "https://www.google.com/maps?q=Brezovica+Kosovo&output=embed",
                ],
            ],
            [
                'id' => 26,
                'category_slug' => "family",
                'destination' => "Switzerland",
                'hero_title' => "Oeschinensee Family Day — Boats & Trails",
                'hero_image' => "https://nextstopadventure.com/wp-content/uploads/2018/07/2018-07-28_0004.jpg",
                'price' => 2890,
                'days' => "7 days",
                'rating' => 4.9,
                'overview' => "Enjoy a magical family day at Lake Oeschinen. Take boat rides, hike scenic trails, and enjoy a picnic by one of Switzerland’s most beautiful alpine lakes.",
                'highlights' => ["Boat Rides", "Family Hikes", "Alpine Picnic"],
                'gallery' => [
                    "https://famigros.migros.ch/.imaging/mte/famigros-web/image_stage_content_xxs/dam/famigros/ausfluege-freizeit/ausflugsziele/oeschinensee/oeschinensee-ausflugsziel-buehnenbild3.jpg/jcr:content/oeschinensee-ausflugsziel-buehnenbild3.jpg",
                    "https://hoptheearth.com/wp-content/uploads/2024/02/Panorama-Trail-Oeschinensee-e1752957730692.jpg",
                    "https://ordinarytraveler.com/wp-content/uploads/2018/10/kandersteg-lake-oeschinensee-travel-guide.jpg",
                ],
                'location' => [
                    'description' => "Located in Bernese Oberland, Switzerland.",
                    'nearestCity' => "Kandersteg",
                    'groupSize' => "4 - 8 People",
                    'bestSeason' => "June – September",
                    'mapSrc' => "https://www.google.com/maps?q=Oeschinensee+Switzerland&output=embed",
                ],
            ],
            [
                'id' => 27,
                'category_slug' => "family",
                'destination' => "USA",
                'hero_title' => "Florida Theme Parks Family Escape",
                'hero_image' => "https://imageio.forbes.com/specials-images/imageserve/6661c678b4ce2a6369e3ac54/0x0.jpg?format=jpg&crop=2560,1573,x0,y133,safe&height=900&width=1600&fit=bounds",
                'price' => 1990,
                'days' => "5 days",
                'rating' => 4.8,
                'overview' => "Enjoy an unforgettable family adventure at Florida’s world-famous theme parks. Meet beloved characters, ride thrilling attractions, and create memories that last a lifetime.",
                'highlights' => ["Theme Parks", "Family Fun", "Beloved Characters"],
                'gallery' => [
                    "https://espnswfl.com/uploads/2023/06/GettyImages-809899932.jpg?format=auto&optimize=high&width=1440",
                    "https://blooloop.com/wp-content/uploads/2022/04/walt-disney-world.jpeg",
                    "https://res.klook.com/images/fl_lossy.progressive,q_65/c_fill,w_1200,h_630/activities/alg3puq4hmpeobqhumjd/WaltDisneyWorldResortTicket-KlookUnitedKingdom.jpg",
                ],
                'location' => [
                    'description' => "Located in Orlando, Florida.",
                    'nearestCity' => "Orlando",
                    'groupSize' => "4 - 10 People",
                    'bestSeason' => "All Year",
                    'mapSrc' => "https://www.google.com/maps?q=Orlando+Florida&output=embed",
                ],
            ],
            [
                'id' => 28,
                'category_slug' => "family",
                'destination' => "Italy",
                'hero_title' => "Tropea & Calabria Coast — Family Beach Days",
                'hero_image' => "https://www.thetimes.com/imageserver/image/%2Fmethode%2Fsundaytimes%2Fprod%2Fweb%2Fbin%2Fbc4c478c-7db2-11e7-a679-872d92606f03.jpg?crop=2250%2C1266%2C0%2C117&resize=1200",
                'price' => 1590,
                'days' => "4 days",
                'rating' => 4.7,
                'overview' => "Relax with your family on the stunning beaches of Tropea in Calabria. Crystal waters, Italian food, and safe sandy shores make it perfect for kids.",
                'highlights' => ["Family Beaches", "Italian Cuisine", "Safe Swimming"],
                'gallery' => [
                    "https://www.orminatours.com/wp-content/uploads/2025/06/Italy-Calabria-Tropea-Former-4th-century-monastery-on-top-of-the-Sanctuary-of-Santa-Maria-Island-Tropea-1024x683.webp",
                    "https://images.winalist.com/blog/wp-content/uploads/2025/07/10122238/adobestock-515729288-1500x945.jpeg",
                    "https://www.inlovewiththemed.com/mednvk/uploads/2023/04/Calabria-A-Haven-for-Travelers-Seeking-Authenticity-and-Adventure.jpeg",
                ],
                'location' => [
                    'description' => "Located in Calabria, Southern Italy.",
                    'nearestCity' => "Tropea",
                    'groupSize' => "2 - 8 People",
                    'bestSeason' => "May – September",
                    'mapSrc' => "https://www.google.com/maps?q=Tropea+Italy&output=embed",
                ],
            ],
            [
                'id' => 29,
                'category_slug' => "family",
                'destination' => "Japan",
                'hero_title' => "Nara Deer Park & Kyoto Family Strolls",
                'hero_image' => "https://cdn.gaijinpot.com/app/uploads/sites/6/2016/04/iStock-499127037.jpg",
                'price' => 1450,
                'days' => "2 days",
                'rating' => 4.8,
                'overview' => "Visit Nara Deer Park where kids can feed friendly deer, then explore Kyoto’s family-friendly neighborhoods. A perfect cultural and nature blend.",
                'highlights' => ["Deer Park", "Kyoto Family Strolls", "Cultural Fun"],
                'gallery' => [
                    "https://preview.redd.it/itap-of-deer-in-nara-japan-v0-66ast1kynzmd1.jpeg?width=640&crop=smart&auto=webp&s=42a3e3166cb79fc33210ae91831d4364445d3bc3",
                    "https://www.thetokyochapter.com/wp-content/uploads/2019/05/feeding-Nara-Deer.jpg",
                    "https://cdn.getyourguide.com/image/format=auto,fit=crop,gravity=auto,quality=60,width=450,height=450,dpr=2/tour_img/d586f7a3e8cb4a2e585685764b4ee8cb84b277dfdee2509a81dc610752c55eb3.jpg",
                ],
                'location' => [
                    'description' => "Located in Nara and Kyoto, Japan.",
                    'nearestCity' => "Kyoto",
                    'groupSize' => "4 - 12 People",
                    'bestSeason' => "April – October",
                    'mapSrc' => "https://www.google.com/maps?q=Nara+Deer+Park&output=embed",
                ],
            ],
            [
                'id' => 30,
                'category_slug' => "family",
                'destination' => "Greece",
                'hero_title' => "Corfu Family Beach Day - Paleokastritsa",
                'hero_image' => "https://as2.ftcdn.net/v2/jpg/01/27/31/47/1000_F_127314769_a8yZvD02yGuwuq0QW6nK5KmjRiZntYSK.jpg",
                'price' => 1390,
                'days' => "3 days",
                'rating' => 4.8,
                'overview' => "Spend a relaxing family day in Paleokastritsa, one of Corfu’s most beautiful coastal spots. Swim in crystal-clear waters, explore hidden coves and sea caves by boat, and stroll along lush bays fringed with olive trees. Add a visit to the hilltop monastery for views over the Ionian Sea, and enjoy Greek food at seaside tavernas - perfect for all ages.",
                'highlights' => ["Family Beach Fun", "Safe Waters", "Sunny Escape"],
                'gallery' => [
                    "https://santorinidave.com/wp-content/uploads/2025/03/corfu-beach-agia-triada.jpeg",
                    "https://www.pelago.com/img/products/GR-Greece/private-shore-excursion-paleokastritsa-and-corfu-old-town/c7281057-751f-4dfb-9488-baef39024c84_private-shore-excursion-paleokastritsa-and-corfu-old-town-xlarge.jpg",
                    "https://media.istockphoto.com/id/1125136780/photo/beach-and-boat-in-paleokastritsa-corfu.jpg?s=612x612&w=0&k=20&c=ZRzRUFakU5Vps-gHDqsKxo7IaZ1XeRJNBfsGF_vfxtk=",
                ],
                'location' => [
                    'description' => "Nestled on Corfu’s northwest coast, Paleokastritsa is famous for turquoise bays, caves, and scenic hillsides, ideal for family beach escapes.",
                    'nearestCity' => "Corfu Town",
                    'groupSize' => "4 – 12 People",
                    'bestSeason' => "May – September",
                    'mapSrc' => "https://www.google.com/maps?q=Paleokastritsa+Corfu&output=embed",
                ],
            ],
        ];

        foreach ($tours as $tour) {
            TourDetail::create($tour);
        }
    }
}
